const superheroNames = [
    "Super Rire-Man",
    "Madame Chatouille",
    "Captain Cafard",
    "L'Homme Fou-rire",
    "Miss Frisette",
    "Super Tourniquet",
    "Docteur Éclat-de-Rire",
    "La Guêpe Farceuse",
    "Monsieur Banane",
    "Miss Bulles",
    "L'Éclair Glouglou",
    "Capitaine Miam-Miam",
    "Mademoiselle Amusement",
    "Super Blagueur",
    "Le Rigolo Volant",
    "Ultra Sourire",
    "La Danseuse Déjantée",
    "Monsieur Farfelu",
    "Miss Canular",
    "Super Chatouille",
    "Le Gaffeur Étoilé",
    "L'Artiste Comique",
    "Madame Rigolote",
    "Monsieur Zigzag",
    "Capitaine Cocorico",
    "La Fou-rire Rose",
    "Miss Toc-Toc",
    "Super Sauterelle",
    "Monsieur Chocolat Fondant",
    "Madame Étoile Filante",
    "Monsieur Zigzag",
  ];
  
  export default superheroNames;
  